### ISSUE TITLE
pandas >= 2.0?

### ISSUE THREAD

**Issue by spencersalazar** [meinardmueller/libfmp#14]
Hi, wondering if its possible to update the `pandas` requirement to allow versions >= 2.0 that was released earlier this year? We are currently having an issue of incompatibility between `libfmp` and packages that require `pandas` 2.0 or higher. 

https://pandas.pydata.org/docs/dev/whatsnew/v2.0.0.html

**Comment by fzalkow** [comment]
Hi, and thanks for reaching out! I relaxed the version requirement for pandas in the commit f884d4d67583c645994d7b39945a6cc6357a0f9a.
