### ISSUE TITLE
Pass `sr` as keyword at `librosa.load`

### ISSUE THREAD

**Issue by progsi** [meinardmueller/libfmp#15]
Thanks for the great work of FMP Notebooks and with this package!
I would like to report a small issue in `c4s2_ssm.py` and possibly other places where `librosa.load` is used. In newer librosa versions, the `sr` parameter name must be specified and hence `librosa.load` does not work.

**Comment by fzalkow** [comment]
Hi Simon, Many thanks for raising this issue.

I wonder, which librosa version you are referring to? The [documentation for the latest version (0.10.2)](https://librosa.org/doc/0.10.2/generated/librosa.load.html#librosa.load) specifies that the audio sample is resampled to 22050 Hz by default. Furthermore, in the [current main branch of the librosa](https://github.com/librosa/librosa/blob/main/librosa/core/audio.py#L61) Github repository, a default sample rate of 22050 Hz is given.

**Comment by progsi** [comment]
Hi Frank, sorry for the late reply. Actually I tested it again and now I cannot reproduce this error. Maybe the most recent version of Librosa changed or it was my fault. So you can probably close this issue :)

**Comment by fzalkow** [comment]
Alright, no problem. Let us know if you experience further issues.
