### ISSUE TITLE
typo: hope should be hop

### ISSUE THREAD

**Issue by expectopatronum** [meinardmueller/libfmp#2]
Hi,
in a [few places](https://github.com/meinardmueller/libfmp/search?q=hope) the description of H is `hope size` instead of `hop size`.

Best regards
Verena

**Comment by fzalkow** [comment]
Hi,
Many thanks for finding these typos. I fixed them (24fa1d3b27f44e4cb9753d2d4536f6566eb934a2). From my point of view, the issue can be closed. Since this is the first issue of the JOSS review process I am taking care of, I don't close it directly but wait for your confirmation.
Best,
Frank
