### ISSUE TITLE
Minor issues in the documentation

### ISSUE THREAD

**Issue by expectopatronum** [meinardmueller/libfmp#3]
Hi again,
while reviewing I noticed a few minor things in the README/documentation:
* I don't see a statement of need in the documentation. There is a detailed statement of need in the paper but the review check list also asks for a statement of need in the documentation.
* The info can be found from setup.py but for me as a user it would be helpful to see at one glance which Python version is required (e.g. in the README in section "Installing")
* Community Guidelines: There is a section regarding contributing, but it does not mention how to "Report issues or problems with the software" or "Seek support", although I would expect it through the same channels (mail to the main author, github issue).

Best regards
Verena

**Comment by fzalkow** [comment]
Many thanks for these points. I addressed them in the commit 1ad21243e3db35e2861356308e4be63acdcbd122.

Best,

Frank

**Comment by expectopatronum** [comment]
Perfect, thanks!
