### ISSUE TITLE
numba version is not compatible with python3.6

### ISSUE THREAD

**Issue by yiitozer** [meinardmueller/libfmp#6]
The numba library version in the requirements (>=0.51.0) doesn't seem to be compatible with Python 3.6. 

Would it be better to update the compatible python versions?

**Comment by fzalkow** [comment]
Hi. Numba 0.51.0 is compatible with Python 3.6. Pleas see: https://pypi.org/project/numba/0.51.0/

There, you find the valid Python versions are 3.6–3.8. So, I would say that we don't have an issue here, right?

**Comment by yiitozer** [comment]
Ah ok, I’ve recently got an error based on that. If the official docs state that, sure there is no issue.

**Comment by fzalkow** [comment]
As a cross-check, I created an environment with Python 3.6 and tried to install numba 0.51.0. It works for me.

```
conda create -n test python=3.6 pip
conda activate test
pip install numba==0.51.0
```
