### ISSUE TITLE
How can I simply get the bpm of popular music through this package

### ISSUE THREAD

**Issue by 980202006** [meinardmueller/libfmp#7]

**Comment by fzalkow** [comment]
Hi,

libfmp goes hand in hand with the [FMP notebooks](https://www.audiolabs-erlangen.de/FMP), where you find extensive documentation on libfmp's functions and its underlying algorithms. There is an entire collection of notebooks relating to beat and tempo (see [C6](https://www.audiolabs-erlangen.de/resources/MIR/FMP/C6/C6.html)). In particular, the notebook on [Beat Tracking by Dynamic Programming](https://www.audiolabs-erlangen.de/resources/MIR/FMP/C6/C6S3_BeatTracking.html) is relevant to your problem.

I hope that serves you as a stater.

Best,

Frank

**Comment by fzalkow** [comment]
Closed due to inactivity.
