### ISSUE TITLE
pysoundfile dependncy

### ISSUE THREAD

**Issue by pkendrick** [meinardmueller/libfmp#8]
This package depends on the old naming of `pysoundfile`, the package was renamed at version 0.8 to just `soundfile`.  Having the old package name as a dependency for this repo means that when other packages have the newer name both are installed, this can cause problems as both packages are imported using `import soundfile`.

I suggest changing the dependency to `soundfile` rather than `pysoundfile`, there is no need to adjust versions as 0.8.x and 0.9.x are available on pypi for both pysoundfile and soundfile, though pysoundfile seems to be no longer available for 0.10.x and above.

I created a fork and ran the tests, with no problem and also tested the save_audio function which worked fine:

https://github.com/pkendrick/libfmp

**Comment by fzalkow** [comment]
Dear @pkendrick, Many thanks for your suggestion. Your fork looks good, and you can open a pull request. Best, Frank

**Comment by pkendrick** [comment]
Thanks @fzalkow, I just raised the PR.

**Comment by fzalkow** [comment]
Many thanks. PR was merged. https://github.com/meinardmueller/libfmp/pull/9
